# Generated by Django 3.0.8 on 2020-08-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=32)),
                ('reading_date', models.DateTimeField()),
                ('soil_moisture_reading', models.IntegerField()),
                ('light_intensity_reading', models.IntegerField()),
                ('water_level_reading', models.IntegerField()),
            ],
        ),
    ]
