# Generated by Django 3.0.8 on 2020-09-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_plant_api', '0004_tokenplantidbind'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=32)),
                ('tokens', models.TextField()),
                ('reason', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
