# Generated by Django 3.0.8 on 2020-09-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_plant_api', '0005_notificationsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsent',
            name='tokens',
        ),
    ]
